/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'status' : BookingStatus,
  'date' : string,
  'name' : string,
  'time' : string,
  'timestamp' : Time,
  'phone' : string,
  'guests' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface Review {
  'reviewText' : string,
  'timestamp' : Time,
  'rating' : bigint,
  'reviewer' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'submitReview' : ActorMethod<[string, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];